project:
  type: website

website:
  title: "Sudesh Bhagat"
  navbar:
    background: primary
    left:
       - text: "Home"
         file: index.qmd
       - About.qmd
       - resources.qmd

format:
  html:
    theme:
      light: minty
      dark: slate
    css: styles.css

editor: visual
