---
title: "Journey So Far"
---

I believe that I was not born into the "tech-age", as my childhood was spent on playgrounds and soccer fields, away from gadgets and technology. Having said that, my interest in technology is anything but new founded. I still remember my first marvel of a cell phone handed to me at the age of 18. After an intense tug of war between curiosity and "responsible behavior" for two whole days, I grabbed my tool box and opened up my phone to understand how it worked. My inexperienced hands could not handle the delicate technology neatly packed in my handset and I was left with hardware junk that had been a working cell phone only two days ago. However, the joy of having had a peek into the inside of this new piece of technology far overshadowed my dejection of having deprived myself of a popular gadget. That day, the seeds of a life-long decision to commit to technology were sown. A few years later, not surprisingly, I graduated with a Bachelor of Science in Information Systems and Networking from United States International University, Nairobi, Kenya. Thereafter, I came to the United States to learn more about Telecommunications and Networking by means of a Master's degree in the field from Ohio University.

As part of my curriculum, I was exposed to exciting subjects such as Information Networks, Development and Telecom, Internet Engineering, Regulation and Policy as well as Research Methods, which helped deepen my interest in the field of Telecommunications and Networking. An integral part of the course was my individual project on Evaluation and Implementation of SIP Protocol on Smart Grid. The project was aimed at addressing the challenges of implementing SIP Protocol on Smart Grid for the utility industry. SIP was recommended as an open standard communication protocol, with special attention to addressing challenges such as security. I also helped develop a presentation on Smart Grid Functionality as Constrained by Network Performance and Security for the EnergyTech11 conference. This presentation primarily focused on the development of an analytical model for Smart Grid delay, among others. Thereafter, I also co-authored a paper on the latency analysis of Smart Grid secure demand response information. The exposure through these projects helped me realize that I wish to understand and study various aspects of Telecommunications and Networking in further detail.
